# Generated by Django 5.0 on 2023-12-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(blank=True, choices=[(0, '男'), (1, '女')], null=True)),
                ('studentNo', models.IntegerField()),
            ],
        ),
    ]
